compose:
  security:
    oauth2:
      wechat:
        wxpa:
          verify-token: ${WXPA_VERIFY_TOKEN}
          app-id: ${WXPA_APP_ID}
          app-secret: ${WXPA_APP_SECRET}
  oss:
    base-url: minio
    expose-base-url: https://${GLOBAL_DOMAIN}/ressources_oss/
    port: ${MINIO_PORT}
    minio:
      enable-https: false
      secret-key: ${MINIO_PASSWORD}
      access-key: ${MINIO_USER}
spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
  data:
    redis:
      host: redis
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  datasource:
    hikari:
      schema: public
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:${PG_PORT}/${PG_DB}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect
